development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:6fc61634a4411255f0858075f8618f0c@sole.redistogo.com:10008/
  channel_prefix: message_me_production
